"""fix role default

Revision ID: 78fc552d941d
Revises: aadf88d7dacf
Create Date: 2026-04-16 17:07:58.310479

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "78fc552d941d"
down_revision: Union[str, Sequence[str], None] = "aadf88d7dacf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
