"""fix role defaultV2

Revision ID: be9a9ad24e56
Revises: 78fc552d941d
Create Date: 2026-04-16 17:09:59.772655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "be9a9ad24e56"
down_revision: Union[str, Sequence[str], None] = "78fc552d941d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
