"""add bookings

Revision ID: 7d3b05493613
Revises: 9f512ede6b45
Create Date: 2026-04-18 18:30:04.325335

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7d3b05493613"
down_revision: Union[str, Sequence[str], None] = "9f512ede6b45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
